import { Recipe, RecipeCategory } from './types';

export const recipes: Recipe[] = [
  // ===== THE PLANT BASED SCHOOL (10 recipes) =====
  {
    title: 'No Bake Oat Bars',
    description: 'Soft and chewy no bake oat bars with nuts, seeds, and cranberries.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/No-bake-oat-bars-with-oats-nuts-seeds-and-cranberries-arranged-on-marble-surface.jpg',
    link: 'https://theplantbasedschool.com/no-bake-oat-bars/',
    category: 'breakfast',
    source: 'The Plant Based School',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Peanut Butter Energy Balls',
    description: 'No-bake peanut butter energy balls served chilled on a marble table.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Peanut-butter-energy-balls-with-chocolate-chips-in-soft-natural-window-light.jpg',
    link: 'https://theplantbasedschool.com/peanut-butter-energy-balls/',
    category: 'snack',
    source: 'The Plant Based School',
    prepTime: '10 mins',
    difficulty: 'easy',
  },
  {
    title: 'Peanut Butter Banana Muffins',
    description: 'Peanut butter banana muffins stacked on marble table with creamy drizzle.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Peanut-butter-banana-muffins-stacked-on-marble-surface-with-drizzle-and-peanuts-in-soft-natural-light.jpg',
    link: 'https://theplantbasedschool.com/peanut-butter-banana-muffins/',
    category: 'breakfast',
    source: 'The Plant Based School',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Chia Pudding Recipes',
    description: 'Three versions of healthy chia pudding recipes.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/3-versions-of-chia-pudding-recipes-you-can-make-for-meal-prep.jpg',
    link: 'https://theplantbasedschool.com/chia-pudding-recipes/',
    category: 'breakfast',
    source: 'The Plant Based School',
    prepTime: '10 mins',
    difficulty: 'easy',
  },
  {
    title: 'Lentil Noodle Soup',
    description: 'Rustic bowl filled with lentil noodle soup and fresh parsley.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/02/Rustic-bowl-of-lentil-noodle-soup-in-bright-natural-window-light.jpg',
    link: 'https://theplantbasedschool.com/lentil-noodle-soup/',
    category: 'soup',
    source: 'The Plant Based School',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Chickpea Noodle Soup',
    description: 'Cozy bowl of chickpea noodle soup served hot with olive oil.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/02/Bowl-of-chickpea-noodle-soup-on-a-table-with-a-spoon-Parmesan-and-crusty-bread-on-the-side.jpg',
    link: 'https://theplantbasedschool.com/chickpea-noodle-soup/',
    category: 'soup',
    source: 'The Plant Based School',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Marry Me Gnocchi',
    description: 'Spoon lifting creamy marry me gnocchi with spinach.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Spoon-lifting-creamy-marry-me-gnocchi-with-spinach-and-sun-dried-tomatoes-in-skillet-on-marble-table.jpg',
    link: 'https://theplantbasedschool.com/marry-me-gnocchi/',
    category: 'pasta',
    source: 'The Plant Based School',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Orzo Primavera',
    description: 'Bowl of orzo primavera with basil and black pepper.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/03/Warm-orzo-primavera-on-marble-surface-with-soft-shadows-and-fresh-herbs-scattered.jpg',
    link: 'https://theplantbasedschool.com/orzo-primavera/',
    category: 'pasta',
    source: 'The Plant Based School',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Falafel Burger',
    description: 'Falafel burger stacked with lettuce, tomato, and sauce.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Two-falafel-burgers-with-lettuce-tomato-red-onion-and-creamy-sauce-in-soft-buns.jpg',
    link: 'https://theplantbasedschool.com/falafel-burger/',
    category: 'dinner',
    source: 'The Plant Based School',
    prepTime: '30 mins',
    difficulty: 'medium',
  },
  {
    title: 'Pinto Bean Salad',
    description: 'Pinto bean salad in simple bowl near window with bright light.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Spoonful-of-fresh-pinto-bean-salad-with-vibrant-vegetables-on-marble-surface-in-soft-daylight.jpg',
    link: 'https://theplantbasedschool.com/pinto-bean-salad/',
    category: 'salad',
    source: 'The Plant Based School',
    prepTime: '20 mins',
    difficulty: 'easy',
  },

  // ===== FROM MY BOWL (10 recipes) =====
  {
    title: 'Easy Roasted Veggie Pasta',
    description: 'Easy roasted veggie pasta with mushrooms.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/04/Roasted_Veggie_Pasta_FromMyBowl-12.jpg',
    link: 'https://frommybowl.com/easy-roasted-veggie-pasta-with-mushrooms/',
    category: 'pasta',
    source: 'From My Bowl',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Sheet Pan Black Bean Quesadillas',
    description: 'Sheet pan black bean corn quesadillas - easy no-chop recipe.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/04/Sheet_Pan_Black_Bean_Corn_Quesadillas_Vegan_FromMyBowl-13.jpg',
    link: 'https://frommybowl.com/sheet-pan-black-bean-corn-quesadillas/',
    category: 'dinner',
    source: 'From My Bowl',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'High Fiber Chia Pudding',
    description: 'Easy high protein chia pudding with no protein powder.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/03/High_Protein_Chia_Pudding_Vegan_FromMyBowl-11.jpg',
    link: 'https://frommybowl.com/high-protein-chia-pudding/',
    category: 'breakfast',
    source: 'From My Bowl',
    prepTime: '10 mins',
    difficulty: 'easy',
  },
  {
    title: 'Baked Raspberry Oatmeal',
    description: 'Healthy baked raspberry oatmeal - easy one dish recipe.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/03/Baked_Raspberry_Oatmeal_Vegan_FromMyBowl-10.jpg',
    link: 'https://frommybowl.com/healthy-baked-raspberry-oatmeal/',
    category: 'breakfast',
    source: 'From My Bowl',
    prepTime: '35 mins',
    difficulty: 'easy',
  },
  {
    title: 'Spinach Artichoke Soup',
    description: 'Spinach artichoke soup with white beans - dairy-free.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/03/Spinach_Artichoke_White_Bean_Soup_FromMyBowl_Vegan-13.jpg',
    link: 'https://frommybowl.com/spinach-artichoke-soup-with-white-beans/',
    category: 'soup',
    source: 'From My Bowl',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Roasted Curry Cauliflower',
    description: 'Roasted curry cauliflower - simple, vibrant, and delicious.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/03/Roasted_Curry_Cauliflower_Vegan_FromMyBowl-14.jpg',
    link: 'https://frommybowl.com/roasted-curry-cauliflower-recipe/',
    category: 'side',
    source: 'From My Bowl',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Yellow Cauliflower Chickpea Curry',
    description: 'Easy yellow cauliflower chickpea curry with coconut milk.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/02/Yellow_Cauliflower_Chickpea_Curry_Vegan_FromMyBowl-13.jpg',
    link: 'https://frommybowl.com/yellow-cauliflower-chickpea-curry/',
    category: 'dinner',
    source: 'From My Bowl',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'One Pan Vegan Massaman Curry',
    description: 'One pan vegan massaman curry with potatoes and tofu.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/02/One_Pan_Vegan_Massaman_Curry_FromMyBowl-13.jpg',
    link: 'https://frommybowl.com/one-pan-vegan-massaman-curry/',
    category: 'dinner',
    source: 'From My Bowl',
    prepTime: '35 mins',
    difficulty: 'medium',
  },
  {
    title: 'Cherry Almond Scones',
    description: 'Easy cherry almond scones with cherry glaze.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/02/Cherry_Almond_Scones_Vegan_FromMyBowl-16.jpg',
    link: 'https://frommybowl.com/cherry-almond-scones/',
    category: 'dessert',
    source: 'From My Bowl',
    prepTime: '30 mins',
    difficulty: 'medium',
  },
  {
    title: 'Lactation Granola',
    description: 'Easy lactation granola - healthy recipe for breastfeeding moms.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/02/Lactation_Granola_FromMyBowl_Vegan-15.jpg',
    link: 'https://frommybowl.com/lactation-granola/',
    category: 'breakfast',
    source: 'From My Bowl',
    prepTime: '35 mins',
    difficulty: 'easy',
  },

  // ===== MINIMALIST BAKER (10 recipes) =====
  {
    title: 'Strawberries & Cream Chia Pudding',
    description: 'Creamy, dairy-free chia pudding with fresh strawberries.',
    image: 'https://minimalistbaker.com/wp-content/uploads/2025/06/Strawberry-Chia-Pudding-5.jpg',
    link: 'https://minimalistbaker.com/strawberry-chia-pudding/',
    category: 'breakfast',
    source: 'Minimalist Baker',
    prepTime: '10 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Sweet Potato Chickpea Taco Salad',
    description: 'Hearty taco salad with roasted sweet potatoes and chickpeas.',
    image: 'https://minimalistbaker.com/wp-content/uploads/2024/05/Vegan-Sweet-Potato-Chickpea-Taco-Salad-7.jpg',
    link: 'https://minimalistbaker.com/vegan-chickpea-taco-salad/',
    category: 'lunch',
    source: 'Minimalist Baker',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Cheesy Jalapeño Cashew Dressing',
    description: 'Spicy, creamy dairy-free dressing perfect for salads and bowls.',
    image: 'https://minimalistbaker.com/wp-content/uploads/2024/05/Vegan-Cashew-Jalapeno-Dressing-4.jpg',
    link: 'https://minimalistbaker.com/vegan-cashew-dressing/',
    category: 'snack',
    source: 'Minimalist Baker',
    prepTime: '5 mins',
    difficulty: 'easy',
  },
  {
    title: 'Fudgy Chocolate Tahini Cookies',
    description: '1-bowl fudgy chocolate cookies made with tahini.',
    image: 'https://minimalistbaker.com/wp-content/uploads/2025/06/Fudgy-Vegan-Chocolate-Tahini-Cookies-7.jpg',
    link: 'https://minimalistbaker.com/chocolate-tahini-cookies/',
    category: 'snack',
    source: 'Minimalist Baker',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Morning Glory Muffins',
    description: 'Hearty gluten-free muffins packed with carrots and apples.',
    image: 'https://minimalistbaker.com/wp-content/uploads/2024/01/Vegan-Gluten-Free-Morning-Glory-Muffins-10.jpg',
    link: 'https://minimalistbaker.com/vegan-gluten-free-morning-glory-muffins/',
    category: 'breakfast',
    source: 'Minimalist Baker',
    prepTime: '35 mins',
    difficulty: 'medium',
  },
  {
    title: 'Creamy Curried Black Eyed Pea Soup',
    description: 'Comforting and flavorful soup with black eyed peas and curry spices.',
    image: 'https://minimalistbaker.com/wp-content/uploads/2025/06/Creamy-Curried-Vegan-Black-Eyed-Bean-Soup-8.jpg',
    link: 'https://minimalistbaker.com/curried-black-eyed-pea-soup/',
    category: 'soup',
    source: 'Minimalist Baker',
    prepTime: '40 mins',
    difficulty: 'easy',
  },
  {
    title: 'Tahini Hot Chocolate',
    description: 'Dreamy, protein-rich hot chocolate made with tahini.',
    image: 'https://minimalistbaker.com/wp-content/uploads/2025/06/Tahini-Hot-Chocolate-6.jpg',
    link: 'https://minimalistbaker.com/tahini-hot-chocolate/',
    category: 'breakfast',
    source: 'Minimalist Baker',
    prepTime: '5 mins',
    difficulty: 'easy',
  },
  {
    title: 'Cranberry Orange Cookie Bars',
    description: 'Festive vegan and gluten-free cookie bars with cranberry and orange.',
    image: 'https://minimalistbaker.com/wp-content/uploads/2023/09/Vegan-Gluten-Free-Cranberry-Orange-Cookie-Bars-9.jpg',
    link: 'https://minimalistbaker.com/cranberry-orange-cookie-bars/',
    category: 'snack',
    source: 'Minimalist Baker',
    prepTime: '45 mins',
    difficulty: 'medium',
  },
  {
    title: '1-Pot Kabocha Chickpea Miso Soup',
    description: 'Cozy miso soup with kabocha squash and chickpeas.',
    image: 'https://minimalistbaker.com/wp-content/uploads/2023/11/1-Pot-Kabocha-Chickpea-Miso-Soup-25-Minimalist-Baker-110323-683x1024.jpg',
    link: 'https://minimalistbaker.com/kabocha-chickpea-miso-soup/',
    category: 'soup',
    source: 'Minimalist Baker',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Easy Gluten-Free Monster Cookies',
    description: 'Flourless monster cookies made with peanut butter and oats.',
    image: 'https://minimalistbaker.com/wp-content/uploads/2025/02/Easy-Gluten-Free-Monster-Cookies-7.jpg',
    link: 'https://minimalistbaker.com/easy-gluten-free-monster-cookies/',
    category: 'snack',
    source: 'Minimalist Baker',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  // ===== RAINBOW PLANT LIFE (10 recipes) =====
  {
    title: 'Chili Oil Peanut Noodles',
    description: 'Spicy chili oil peanut noodles in 20 minutes.',
    image: 'https://plantyou.com/wp-content/uploads/2026/03/DSC06924-scaled.jpg',
    link: 'https://plantyou.com/chili-oil-peanut-noodles/',
    category: 'pasta',
    source: 'Rainbow Plant Life',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Easy Vegan Alfredo Pasta',
    description: 'One pot creamy vegan pasta with herbs.',
    image: 'https://plantyou.com/wp-content/uploads/2026/03/DSC06511-scaled.jpg',
    link: 'https://plantyou.com/easy-vegan-alfredo-pasta/',
    category: 'pasta',
    source: 'Rainbow Plant Life',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'One Pot Creamy Pasta',
    description: 'One pot creamy vegan pasta with vegan parmesan.',
    image: 'https://plantyou.com/wp-content/uploads/2026/01/DSC03633-scaled.jpg',
    link: 'https://plantyou.com/one-pot-creamy-pasta/',
    category: 'pasta',
    source: 'Rainbow Plant Life',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Thai Noodle Salad',
    description: 'Meal prep Thai noodle salad in a jar.',
    image: 'https://plantyou.com/wp-content/uploads/2025/06/DSC03615.jpg',
    link: 'https://plantyou.com/thai-noodle-salad/',
    category: 'salad',
    source: 'Rainbow Plant Life',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Marry Me Chickpeas',
    description: 'Creamy marry me chickpeas - one pan wonder.',
    image: 'https://plantyou.com/wp-content/uploads/2025/04/DSC01281.png',
    link: 'https://plantyou.com/marry-me-chickpeas/',
    category: 'dinner',
    source: 'Rainbow Plant Life',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Creamy Cucumber Salad',
    description: 'Creamy cucumber salad with dill and lemon.',
    image: 'https://plantyou.com/wp-content/uploads/2025/02/DSC08582.png',
    link: 'https://plantyou.com/vegan-creamy-cucumber-salad/',
    category: 'salad',
    source: 'Rainbow Plant Life',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Deviled Strawberries',
    description: 'Deviled strawberries with graham cracker crumbs.',
    image: 'https://plantyou.com/wp-content/uploads/2025/04/DSC00954.png',
    link: 'https://plantyou.com/deviled-strawberries/',
    category: 'dessert',
    source: 'Rainbow Plant Life',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Carrot and Cucumber Salad',
    description: 'Carrot and cucumber salad with lemon dressing.',
    image: 'https://plantyou.com/wp-content/uploads/2026/02/DSC04584-scaled.jpg',
    link: 'https://plantyou.com/carrot-and-cucumber-salad/',
    category: 'salad',
    source: 'Rainbow Plant Life',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Lentil Patties',
    description: 'Lentil patties with creamy vegan dip.',
    image: 'https://plantyou.com/wp-content/uploads/2026/01/DSC04272-scaled.jpg',
    link: 'https://plantyou.com/lentil-patties/',
    category: 'dinner',
    source: 'Rainbow Plant Life',
    prepTime: '35 mins',
    difficulty: 'medium',
  },
  {
    title: 'Vegan Pistachio Ice Cream',
    description: 'Vegan pistachio ice cream in white ramekin.',
    image: 'https://plantyou.com/wp-content/uploads/2025/07/DSC05998.jpg',
    link: 'https://plantyou.com/vegan-pistachio-ice-cream/',
    category: 'dessert',
    source: 'Rainbow Plant Life',
    prepTime: '20 mins + freeze',
    difficulty: 'medium',
  },

  // ===== PLANT-BASED ON A BUDGET (10 recipes) =====
  {
    title: 'Sticky Lemon Tofu',
    description: 'Sticky lemon tofu - easy vegan dinner.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/06/Lemon-Tofu-11.jpg',
    link: 'https://plantbasedonabudget.com/sticky-lemon-tofu/',
    category: 'dinner',
    source: 'Plant-Based on a Budget',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Chipotle Chili Recipe',
    description: 'Spicy chipotle bean chili in a bowl.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/08/Chipotle-Bean-Chili-PBOAB-15.jpg',
    link: 'https://plantbasedonabudget.com/chipotle-chili-recipe/',
    category: 'soup',
    source: 'Plant-Based on a Budget',
    prepTime: '35 mins',
    difficulty: 'easy',
  },
  {
    title: 'Cream of Celery Soup',
    description: 'Creamy celery soup in a bowl.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/09/Celery-Soup-11.jpg',
    link: 'https://plantbasedonabudget.com/cream-of-celery-soup/',
    category: 'soup',
    source: 'Plant-Based on a Budget',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Easy Lentil Salad',
    description: 'Easy lentil salad on a plate.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/02/Lentil-Salad-PBOAB-14.jpg',
    link: 'https://plantbasedonabudget.com/easy-lentil-salad/',
    category: 'salad',
    source: 'Plant-Based on a Budget',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Lemongrass Tofu',
    description: 'Lemongrass tofu on a plate.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/05/Lemongrass-Tofu-14.jpg',
    link: 'https://plantbasedonabudget.com/lemongrass-tofu/',
    category: 'dinner',
    source: 'Plant-Based on a Budget',
    prepTime: '30 mins',
    difficulty: 'medium',
  },
  {
    title: 'Easy Curried Chickpea Salad',
    description: 'Easy curried chickpea salad on a plate.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/02/Curried-Chickpea-Salad-Plant-Based-on-a-Budget-13.jpg',
    link: 'https://plantbasedonabudget.com/easy-curried-chickpea-salad/',
    category: 'salad',
    source: 'Plant-Based on a Budget',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Alphabet Soup Recipe',
    description: 'Fun alphabet soup in a bowl.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/02/Alphabet-Soup-PBOAB-15.jpg',
    link: 'https://plantbasedonabudget.com/alphabet-soup-recipe/',
    category: 'soup',
    source: 'Plant-Based on a Budget',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Easy Tempeh Tacos',
    description: 'Easy tempeh tacos on a white surface.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2024/06/Tempeh-Tacos-PBOAB-Plant-Based-on-a-Budget-42.jpg',
    link: 'https://plantbasedonabudget.com/easy-tempeh-tacos/',
    category: 'dinner',
    source: 'Plant-Based on a Budget',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Peanut Butter Cake',
    description: 'Vegan peanut butter cake on a plate.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/08/Peanut-Butter-Cake-18.jpg',
    link: 'https://plantbasedonabudget.com/vegan-peanut-butter-cake/',
    category: 'dessert',
    source: 'Plant-Based on a Budget',
    prepTime: '40 mins',
    difficulty: 'medium',
  },
  {
    title: 'Gingerbread Crinkle Cookies',
    description: 'Gingerbread crinkle cookies on a baking dish.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/10/Ginger-Crinkle-Cookies-PBOAB-17.jpg',
    link: 'https://plantbasedonabudget.com/gingerbread-crinkle-cookies-eggless/',
    category: 'dessert',
    source: 'Plant-Based on a Budget',
    prepTime: '25 mins',
    difficulty: 'easy',
  },

  // ===== SWEET POTATO SOUL (10 recipes) =====
  {
    title: 'Sweet Potato Chickpea Curry',
    description: 'Hearty chickpea curry with sweet potatoes and coconut milk.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2025/04/sweet-potato-chickpea-social-graphic.png',
    link: 'https://sweetpotatosoul.com/sweet-potato-chickpea-curry/',
    category: 'dinner',
    source: 'Sweet Potato Soul',
    prepTime: '35 mins',
    difficulty: 'easy',
  },
  {
    title: 'Easy Vegan Lentil Tacos',
    description: 'Easy lentil tacos ready in 10 minutes.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2024/01/Easy-Lentil-Tacos.jpg',
    link: 'https://sweetpotatosoul.com/sculpting-kitchen-workout-lentil-tacos-with-mango-guacamole-video/',
    category: 'dinner',
    source: 'Sweet Potato Soul',
    prepTime: '10 mins',
    difficulty: 'easy',
  },
  {
    title: 'Chickpea Tuna Salad',
    description: 'Vegan chickpea tuna salad - creamy and zesty.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2024/04/chickpea-tuna-salad-graphic.png',
    link: 'https://sweetpotatosoul.com/vegan-chickpea-tuna-salad-video/',
    category: 'lunch',
    source: 'Sweet Potato Soul',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Jamaican Chickpea Curry',
    description: 'Spicy Jamaican curry with chickpeas.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2025/09/jamaican-chickpea-curry.jpg',
    link: 'https://sweetpotatosoul.com/jamaican-chickpea-curry/',
    category: 'dinner',
    source: 'Sweet Potato Soul',
    prepTime: '30 mins',
    difficulty: 'medium',
  },
  {
    title: 'Vegan Lentil Meatloaf',
    description: 'Hearty vegan lentil meatloaf with mushroom gravy.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2024/05/vegan-lentil-meatloaf.jpeg',
    link: 'https://sweetpotatosoul.com/vegan-lentil-meatloaf/',
    category: 'dinner',
    source: 'Sweet Potato Soul',
    prepTime: '50 mins',
    difficulty: 'medium',
  },
  {
    title: 'Vegan Burrito Bowl',
    description: 'Better-than-Chipotle vegan burrito bowl.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2020/02/Vegan-Taco-Bowl.jpeg',
    link: 'https://sweetpotatosoul.com/ultimate-vegan-burrito-bowl/',
    category: 'dinner',
    source: 'Sweet Potato Soul',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Caesar Salad',
    description: 'Best vegan Caesar salad with crispy chickpeas.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2024/05/vegan-caesar-salad.jpeg',
    link: 'https://sweetpotatosoul.com/best-vegan-caesar-salad/',
    category: 'salad',
    source: 'Sweet Potato Soul',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Fried Chicken',
    description: 'Vegan fried cauliflower "chicken" with double batter.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2017/04/Cauliflower-Vegan-Fried-Chicken.jpeg',
    link: 'https://sweetpotatosoul.com/vegan-fried-cauliflower-chicken-soul-food-sunday-video/',
    category: 'dinner',
    source: 'Sweet Potato Soul',
    prepTime: '40 mins',
    difficulty: 'hard',
  },
  {
    title: 'Sweet Potato Soup',
    description: 'Creamy sweet potato soup with crispy white beans.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2024/11/Sweet-Potato-Soup-Discover-Image.png',
    link: 'https://sweetpotatosoul.com/sweet-potato-bisque-with-crispy-white-beans/',
    category: 'soup',
    source: 'Sweet Potato Soul',
    prepTime: '35 mins',
    difficulty: 'easy',
  },
  {
    title: 'Mango Sorbet',
    description: 'Easy 3-ingredient mango sorbet - no ice cream maker.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2025/05/no-churn-mango-sorbet.jpg',
    link: 'https://sweetpotatosoul.com/mango-sorbet/',
    category: 'dessert',
    source: 'Sweet Potato Soul',
    prepTime: '10 mins + freeze',
    difficulty: 'easy',
  },

  // ===== PLANT BASED RD (10 recipes) =====
  {
    title: 'Dan Dan Charred Cabbage',
    description: 'Charred cabbage with Dan Dan sauce, tofu, and peanuts.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2025/05/Dan-Dan-Charred-Cabbage.jpg',
    link: 'https://plantbasedrdblog.com/2025/05/dan-dan-charred-cabbage/',
    category: 'dinner',
    source: 'Plant Based RD',
    prepTime: '30 mins',
    difficulty: 'medium',
  },
  {
    title: 'Charred Lemon Brothy Beans',
    description: 'White beans with charred lemon and avocado salsa.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2025/01/Charred-Lemon-Brothy-Beans.jpg',
    link: 'https://plantbasedrdblog.com/2025/01/charred-lemon-brothy-beans/',
    category: 'dinner',
    source: 'Plant Based RD',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Pumpkin Coffee Cake Chia Pudding',
    description: 'Pumpkin chia pudding with streusel topping.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2025/09/Pumpkin-Coffee-Cake-Chia-Pudding.jpg',
    link: 'https://plantbasedrdblog.com/2025/09/pumpkin-coffee-cake-chia-pudding/',
    category: 'breakfast',
    source: 'Plant Based RD',
    prepTime: '15 mins + chill',
    difficulty: 'easy',
  },
  {
    title: 'Whole Roasted Cauliflower',
    description: 'Whole roasted cauliflower with scallion date dressing.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2025/02/Whole-Roasted-Cauliflower.jpg',
    link: 'https://plantbasedrdblog.com/2025/02/whole-roasted-cauliflower-with-creamy-scallion-date-dressing/',
    category: 'dinner',
    source: 'Plant Based RD',
    prepTime: '45 mins',
    difficulty: 'medium',
  },
  {
    title: 'Chipotle Lime Black Bean Bowls',
    description: 'Black bean bowls with chipotle lime sauce.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2023/12/chipotle-lime-black-bean-bowls_feat.jpg',
    link: 'https://plantbasedrdblog.com/2023/12/chipotle-lime-black-bean-bowls/',
    category: 'lunch',
    source: 'Plant Based RD',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Chili Lime Chickpea Cauliflower Wrap',
    description: 'Pita wrap with chickpeas, cauliflower, and chipotle.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2024/01/chili-lime-roasted-cauliflower-chickpeas_feat.jpg',
    link: 'https://plantbasedrdblog.com/2024/01/chili-lime-chickpea-cauliflower-wrap/',
    category: 'lunch',
    source: 'Plant Based RD',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Marinated Cilantro Lime Bean Salad',
    description: 'Marinated bean salad with cilantro and lime.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2025/05/Marinated-Cilantro-Lime-Bean-Salad.jpg',
    link: 'https://plantbasedrdblog.com/2025/05/marinated-cilantro-lime-bean-salad/',
    category: 'salad',
    source: 'Plant Based RD',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Black Bean Taquitos',
    description: 'Black bean taquitos with salsa roja.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2025/05/black-bean-taquitos.jpg',
    link: 'https://plantbasedrdblog.com/2025/05/black-bean-taquitos-with-salsa-roja/',
    category: 'appetizer',
    source: 'Plant Based RD',
    prepTime: '30 mins',
    difficulty: 'medium',
  },
  {
    title: 'Caramelized Onion Chickpea Salad Sandwich',
    description: 'Sandwich with caramelized onions and chickpea salad.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2024/03/caramelized-onion-chickpea-salad-sandwich_feat.jpg',
    link: 'https://plantbasedrdblog.com/2024/03/caramelized-onion-chickpea-salad-sandwich/',
    category: 'lunch',
    source: 'Plant Based RD',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Buffalo Tofu Cutlets',
    description: 'Buffalo tofu cutlets with celery ranch slaw.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2024/07/buffalo-tofu-cutlets_feat.jpg',
    link: 'https://plantbasedrdblog.com/2024/07/buffalo-tofu-cutlets-with-celery-ranch-slaw/',
    category: 'dinner',
    source: 'Plant Based RD',
    prepTime: '30 mins',
    difficulty: 'medium',
  },

  // ===== IT DOESN'T TASTE LIKE CHICKEN (10 recipes) =====
  {
    title: 'Loaded Vegan Nachos',
    description: 'Sheet pan of loaded vegan nachos.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2015/08/Vegan-Nachos-facebook.jpg',
    link: 'https://itdoesnttastelikechicken.com/loaded-vegan-nachos/',
    category: 'appetizer',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Dense Bean Salad',
    description: 'Bowl of dense bean salad.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2026/03/Dense-Bean-Salad-facebook.jpg',
    link: 'https://itdoesnttastelikechicken.com/dense-bean-salad/',
    category: 'salad',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Cheesy Vegan Garlic Bread',
    description: 'Two loaves of vegan garlic bread.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2019/02/Vegan-Garlic-Bread-facebook.jpg',
    link: 'https://itdoesnttastelikechicken.com/cheesy-vegan-garlic-bread/',
    category: 'side',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Air Fryer Sweet Potatoes',
    description: 'Platter of air fryer sweet potatoes.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2026/03/Air-Fryer-Sweet-Potatoes-facebook.jpg',
    link: 'https://itdoesnttastelikechicken.com/air-fryer-sweet-potatoes/',
    category: 'side',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Crunchy Roasted Chickpeas',
    description: 'Crispy crunchy roasted chickpeas seasoned with chili powder and thyme.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2018/01/Crispy-Crunchy-Roasted-Chickpeas-recipe-vegan-snack-easy-healthy.jpg',
    link: 'https://itdoesnttastelikechicken.com/crunchy-roasted-chickpeas/',
    category: 'snack',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '5 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vanilla Mug Cake',
    description: 'Mug cake with sprinkles and whipped cream.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2026/03/Vanilla-Mug-Cake-facebook.jpg',
    link: 'https://itdoesnttastelikechicken.com/vanilla-mug-cake/',
    category: 'dessert',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '5 mins',
    difficulty: 'easy',
  },
  {
    title: 'Fudgy Vegan Brownies',
    description: 'Ultra-chocolatey, decadent one-bowl brownies.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2021/03/fudgy-vegan-brownies-recipe-easy-one-bowl-chocolatey-decadant-chewy-facebook.jpg',
    link: 'https://itdoesnttastelikechicken.com/easy-fudgy-vegan-brownies/',
    category: 'dessert',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '35 mins',
    difficulty: 'easy',
  },
  {
    title: 'Easy Red Lentil Curry',
    description: 'Quick, creamy, flavorful curry ready in 40 minutes.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2025/01/easy-red-lentil-curry-recipe-coconut-vegan-vegetarian-Indian-dal-Thai-instant-pot-slow-cooker-facebook.jpg',
    link: 'https://itdoesnttastelikechicken.com/easy-red-lentil-curry/',
    category: 'dinner',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '40 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Egg Roll in a Bowl',
    description: 'Tastes like egg rolls but without the wrapper.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2020/08/vegan-egg-roll-in-a-bowl-vegetarian-easy-facebook.jpg',
    link: 'https://itdoesnttastelikechicken.com/vegan-egg-roll-in-a-bowl/',
    category: 'dinner',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Easy Vegan Zucchini Bread',
    description: 'Moist, tender, fluffy zucchini bread with cinnamon.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2018/07/vegan-zucchini-bread-recipe-easy-best-simple-moist-facebook.jpg',
    link: 'https://itdoesnttastelikechicken.com/easy-vegan-zucchini-bread/',
    category: 'breakfast',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '70 mins',
    difficulty: 'easy',
  },

  // ===== THAT VEGAN BABE (10 recipes) =====
  {
    title: 'Sheet Pan Gnocchi',
    description: 'Sheet pan gnocchi with tahini herb sauce.',
    image: 'https://thatveganbabe.com/wp-content/uploads/2025/10/sheet-pan-gnocchi.jpg',
    link: 'https://thatveganbabe.com/sheet-pan-gnocchi/',
    category: 'pasta',
    source: 'That Vegan Babe',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Caprese Toast',
    description: 'Caprese toast with tomatoes and basil.',
    image: 'https://thatveganbabe.com/wp-content/uploads/2025/05/caprese-toast-recipe.jpg',
    link: 'https://thatveganbabe.com/caprese-toast/',
    category: 'breakfast',
    source: 'That Vegan Babe',
    prepTime: '10 mins',
    difficulty: 'easy',
  },
  {
    title: 'Kale Pesto Pasta',
    description: 'Kale pesto pasta - 15 minute meal.',
    image: 'https://thatveganbabe.com/wp-content/uploads/2025/03/kale-pesto-pasta.jpg',
    link: 'https://thatveganbabe.com/kale-pesto-pasta/',
    category: 'pasta',
    source: 'That Vegan Babe',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Lemon Blueberry Breakfast Cake',
    description: 'Lemon blueberry breakfast cake.',
    image: 'https://i0.wp.com/thatveganbabe.com/wp-content/uploads/easyindex/280x280/thumb-14782.jpg?w=1200',
    link: 'https://thatveganbabe.com/lemon-blueberry-breakfast-cake/',
    category: 'breakfast',
    source: 'That Vegan Babe',
    prepTime: '35 mins',
    difficulty: 'medium',
  },
  {
    title: 'Chocolate Breakfast Quinoa Bake',
    description: 'Chocolate breakfast quinoa bake.',
    image: 'https://thatveganbabe.com/wp-content/uploads/2026/01/chocolate-breakfast-quinoa-bake.jpg',
    link: 'https://thatveganbabe.com/chocolate-breakfast-quinoa-bake/',
    category: 'breakfast',
    source: 'That Vegan Babe',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Tiramisu Baked Oats',
    description: 'Tiramisu flavored baked oats.',
    image: 'https://thatveganbabe.com/wp-content/uploads/2026/01/tiramisu-baked-oats.jpg',
    link: 'https://thatveganbabe.com/tiramisu-baked-oats/',
    category: 'breakfast',
    source: 'That Vegan Babe',
    prepTime: '35 mins',
    difficulty: 'easy',
  },
  {
    title: 'Homemade Collagen Gummies',
    description: 'Healthy homemade collagen gummies.',
    image: 'https://i0.wp.com/thatveganbabe.com/wp-content/uploads/easyindex/280x280/thumb-14579.jpg?w=1200',
    link: 'https://thatveganbabe.com/homemade-collagen-gummies/',
    category: 'snack',
    source: 'That Vegan Babe',
    prepTime: '20 mins + set',
    difficulty: 'medium',
  },
  {
    title: 'Easy Protein Cinnamon Rolls',
    description: 'High protein cinnamon rolls.',
    image: 'https://thatveganbabe.com/wp-content/uploads/2025/11/protein-cinnamon-rolls.jpg',
    link: 'https://thatveganbabe.com/protein-cinnamon-rolls/',
    category: 'dessert',
    source: 'That Vegan Babe',
    prepTime: '45 mins',
    difficulty: 'medium',
  },
  {
    title: 'Viral Chocolate Rice Pudding',
    description: 'Viral chocolate rice pudding.',
    image: 'https://thatveganbabe.com/wp-content/uploads/2025/03/rice-pudding-recipe.jpg',
    link: 'https://thatveganbabe.com/chocolate-rice-pudding/',
    category: 'dessert',
    source: 'That Vegan Babe',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Tiramisu Protein Balls',
    description: 'Tiramisu flavored protein balls.',
    image: 'https://thatveganbabe.com/wp-content/uploads/2025/04/tiramisu-protein-balls.jpg',
    link: 'https://thatveganbabe.com/tiramisu-protein-balls/',
    category: 'snack',
    source: 'That Vegan Babe',
    prepTime: '15 mins',
    difficulty: 'easy',
  },

  // ===== LOVE AND LEMONS (10 recipes) =====
  {
    title: 'Creamy Vegan Pasta',
    description: 'Creamy vegan pasta packed with white beans, nutritional yeast, and lemon juice.',
    image: 'https://cdn.loveandlemons.com/wp-content/uploads/opengraph/2017/10/vegan-pasta.jpg',
    link: 'https://www.loveandlemons.com/vegan-pasta/',
    category: 'pasta',
    source: 'Love and Lemons',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Lentil Pasta',
    description: 'Lentils add plant-based protein to this flavorful vegan pasta.',
    image: 'https://cdn.loveandlemons.com/wp-content/uploads/opengraph/2023/01/lentil-pasta-2.jpg',
    link: 'https://www.loveandlemons.com/lentil-pasta/',
    category: 'pasta',
    source: 'Love and Lemons',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Creamy Butternut Squash Pasta',
    description: 'Comfort in a bowl! Blended squash, roasted garlic, sage, and thyme.',
    image: 'https://cdn.loveandlemons.com/wp-content/uploads/opengraph/2020/10/butternut-squash-pasta-1.jpg',
    link: 'https://www.loveandlemons.com/butternut-squash-pasta/',
    category: 'pasta',
    source: 'Love and Lemons',
    prepTime: '40 mins',
    difficulty: 'medium',
  },
  {
    title: 'Spaghetti Aglio e Olio',
    description: '10-ingredient pasta with bright, fresh lemon zest and parsley.',
    image: 'https://cdn.loveandlemons.com/wp-content/uploads/opengraph/2020/03/spaghetti-aglio-e-olio.jpg',
    link: 'https://www.loveandlemons.com/spaghetti-aglio-e-olio/',
    category: 'pasta',
    source: 'Love and Lemons',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Mac and Cheese',
    description: 'Incredibly creamy and cheesy vegan mac and cheese.',
    image: 'https://cdn.loveandlemons.com/wp-content/uploads/opengraph/2013/01/vegan-mac-and-cheese.jpg',
    link: 'https://www.loveandlemons.com/vegan-mac-and-cheese/',
    category: 'pasta',
    source: 'Love and Lemons',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Tacos',
    description: 'Saucy jackfruit mimics jerk-spiced chicken in these hearty vegan tacos.',
    image: 'https://cdn.loveandlemons.com/wp-content/uploads/opengraph/2019/06/IMG_19042-2.jpg',
    link: 'https://www.loveandlemons.com/vegan-tacos/',
    category: 'dinner',
    source: 'Love and Lemons',
    prepTime: '35 mins',
    difficulty: 'medium',
  },
  {
    title: 'Vegan Enchiladas',
    description: 'Black beans, mushrooms, and poblano peppers create a hearty filling.',
    image: 'https://cdn.loveandlemons.com/wp-content/uploads/opengraph/2024/02/vegan-enchiladas-1.jpg',
    link: 'https://www.loveandlemons.com/vegan-enchiladas/',
    category: 'dinner',
    source: 'Love and Lemons',
    prepTime: '45 mins',
    difficulty: 'medium',
  },
  {
    title: 'Vegan Burrito',
    description: 'Packed with Spanish rice, black beans, pickled onions, and guacamole.',
    image: 'https://cdn.loveandlemons.com/wp-content/uploads/opengraph/2023/05/vegan-burrito-1.jpg',
    link: 'https://www.loveandlemons.com/vegan-burrito/',
    category: 'dinner',
    source: 'Love and Lemons',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Ultimate Sheet Pan Nachos',
    description: 'Smothered with creamy vegan cheese sauce, avocado, and pico de gallo.',
    image: 'https://cdn.loveandlemons.com/wp-content/uploads/opengraph/2020/01/nachos.jpg',
    link: 'https://www.loveandlemons.com/nachos-recipe/',
    category: 'snack',
    source: 'Love and Lemons',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Best Veggie Burger',
    description: 'Hearty, satisfying, and packed with umami flavor made with mushrooms.',
    image: 'https://cdn.loveandlemons.com/wp-content/uploads/opengraph/2018/06/veggie-burger.jpg',
    link: 'https://www.loveandlemons.com/best-veggie-burger-recipe/',
    category: 'dinner',
    source: 'Love and Lemons',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
];

export function getRecipeForFood(foodName: string): Recipe | undefined {
  const nameLower = foodName.toLowerCase()
  return recipes.find(r => 
    r.title.toLowerCase().includes(nameLower) || 
    r.description.toLowerCase().includes(nameLower)
  )
}
