import { Recipe, RecipeCategory } from './types';

export const recipes: Recipe[] = [
  // ===== THE PLANT BASED SCHOOL (10 recipes) =====
  {
    title: 'No Bake Oat Bars',
    description: 'Soft and chewy no bake oat bars with nuts, seeds, and cranberries.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Soft-and-chewy-no-bake-oat-bars-with-nuts-seeds-and-cranberries-on-a-marble-countertop-600x600.jpg',
    link: 'https://theplantbasedschool.com/no-bake-oat-bars/',
    category: 'breakfast',
    source: 'The Plant Based School',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Peanut Butter Energy Balls',
    description: 'No-bake peanut butter energy balls served chilled on a marble table.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/No-bake-peanut-butter-energy-balls-served-chilled-on-a-marble-table-600x600.jpg',
    link: 'https://theplantbasedschool.com/peanut-butter-energy-balls/',
    category: 'snack',
    source: 'The Plant Based School',
    prepTime: '10 mins',
    difficulty: 'easy',
  },
  {
    title: 'Peanut Butter Banana Muffins',
    description: 'Peanut butter banana muffins stacked on marble table with creamy drizzle.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Peanut-butter-banana-muffins-stacked-on-marble-table-with-creamy-drizzle-and-oats-in-soft-natural-light-600x600.jpg',
    link: 'https://theplantbasedschool.com/peanut-butter-banana-muffins/',
    category: 'breakfast',
    source: 'The Plant Based School',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Chia Pudding Recipes',
    description: 'Three versions of healthy chia pudding recipes.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Three-versions-of-healthy-chia-pudding-recipes-600x600.jpg',
    link: 'https://theplantbasedschool.com/chia-pudding-recipes/',
    category: 'breakfast',
    source: 'The Plant Based School',
    prepTime: '10 mins',
    difficulty: 'easy',
  },
  {
    title: 'Lentil Noodle Soup',
    description: 'Rustic bowl filled with lentil noodle soup and fresh parsley.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/02/Rustic-bowl-filled-with-lentil-noodle-soup-and-fresh-parsley-on-top-600x600.jpg',
    link: 'https://theplantbasedschool.com/lentil-noodle-soup/',
    category: 'soup',
    source: 'The Plant Based School',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Chickpea Noodle Soup',
    description: 'Cozy bowl of chickpea noodle soup served hot with olive oil.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/02/Cozy-bowl-of-chickpea-noodle-soup-served-hot-with-olive-oil-and-grated-Parmesan-600x600.jpg',
    link: 'https://theplantbasedschool.com/chickpea-noodle-soup/',
    category: 'soup',
    source: 'The Plant Based School',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Marry Me Gnocchi',
    description: 'Spoon lifting creamy marry me gnocchi with spinach.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Spoon-lifting-creamy-marry-me-gnocchi-showing-soft-texture-and-rich-sauce-with-spinach-600x600.jpg',
    link: 'https://theplantbasedschool.com/marry-me-gnocchi/',
    category: 'pasta',
    source: 'The Plant Based School',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Orzo Primavera',
    description: 'Bowl of orzo primavera with basil and black pepper.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/03/Bowl-of-orzo-primavera-with-basil-and-black-pepper-600x600.jpg',
    link: 'https://theplantbasedschool.com/orzo-primavera/',
    category: 'pasta',
    source: 'The Plant Based School',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Falafel Burger',
    description: 'Falafel burger stacked with lettuce, tomato, and sauce.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Falafel-burger-stacked-with-lettuce-tomato-and-sauce-styled-on-marble-in-bright-light-600x600.jpg',
    link: 'https://theplantbasedschool.com/falafel-burger/',
    category: 'dinner',
    source: 'The Plant Based School',
    prepTime: '30 mins',
    difficulty: 'medium',
  },
  {
    title: 'Pinto Bean Salad',
    description: 'Pinto bean salad in simple bowl near window with bright light.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Pinto-bean-salad-served-in-simple-bowl-near-window-with-bright-natural-light-and-fresh-colors-600x600.jpg',
    link: 'https://theplantbasedschool.com/pinto-bean-salad/',
    category: 'salad',
    source: 'The Plant Based School',
    prepTime: '20 mins',
    difficulty: 'easy',
  },

  // ===== FROM MY BOWL (10 recipes) =====
  {
    title: 'Easy Roasted Veggie Pasta',
    description: 'Easy roasted veggie pasta with mushrooms.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/04/Roasted_Veggie_Pasta_FromMyBowl-12-168x168.jpg',
    link: 'https://frommybowl.com/easy-roasted-veggie-pasta-with-mushrooms/',
    category: 'pasta',
    source: 'From My Bowl',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Sheet Pan Black Bean Quesadillas',
    description: 'Sheet pan black bean corn quesadillas - easy no-chop recipe.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/04/Sheet_Pan_Black_Bean_Corn_Quesadillas_Vegan_FromMyBowl-13-168x168.jpg',
    link: 'https://frommybowl.com/sheet-pan-black-bean-corn-quesadillas/',
    category: 'dinner',
    source: 'From My Bowl',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'High Fiber Chia Pudding',
    description: 'Easy high protein chia pudding with no protein powder.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/03/High_Protein_Chia_Pudding_Vegan_FromMyBowl-11-168x168.jpg',
    link: 'https://frommybowl.com/high-protein-chia-pudding/',
    category: 'breakfast',
    source: 'From My Bowl',
    prepTime: '10 mins',
    difficulty: 'easy',
  },
  {
    title: 'Baked Raspberry Oatmeal',
    description: 'Healthy baked raspberry oatmeal - easy one dish recipe.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/03/Baked_Raspberry_Oatmeal_Vegan_FromMyBowl-10-168x168.jpg',
    link: 'https://frommybowl.com/healthy-baked-raspberry-oatmeal/',
    category: 'breakfast',
    source: 'From My Bowl',
    prepTime: '35 mins',
    difficulty: 'easy',
  },
  {
    title: 'Spinach Artichoke Soup',
    description: 'Spinach artichoke soup with white beans - dairy-free.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/03/Spinach_Artichoke_White_Bean_Soup_FromMyBowl_Vegan-13-168x168.jpg',
    link: 'https://frommybowl.com/spinach-artichoke-soup-with-white-beans/',
    category: 'soup',
    source: 'From My Bowl',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Roasted Curry Cauliflower',
    description: 'Roasted curry cauliflower - simple, vibrant, and delicious.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/03/Roasted_Curry_Cauliflower_Vegan_FromMyBowl-14-168x168.jpg',
    link: 'https://frommybowl.com/roasted-curry-cauliflower-recipe/',
    category: 'side',
    source: 'From My Bowl',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Yellow Cauliflower Chickpea Curry',
    description: 'Easy yellow cauliflower chickpea curry with coconut milk.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/02/Yellow_Cauliflower_Chickpea_Curry_Vegan_FromMyBowl-13-168x168.jpg',
    link: 'https://frommybowl.com/yellow-cauliflower-chickpea-curry/',
    category: 'dinner',
    source: 'From My Bowl',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'One Pan Vegan Massaman Curry',
    description: 'One pan vegan massaman curry with potatoes and tofu.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/02/One_Pan_Vegan_Massaman_Curry_FromMyBowl-13-168x168.jpg',
    link: 'https://frommybowl.com/one-pan-vegan-massaman-curry/',
    category: 'dinner',
    source: 'From My Bowl',
    prepTime: '35 mins',
    difficulty: 'medium',
  },
  {
    title: 'Cherry Almond Scones',
    description: 'Easy cherry almond scones with cherry glaze.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/02/Cherry_Almond_Scones_Vegan_FromMyBowl-16-168x168.jpg',
    link: 'https://frommybowl.com/cherry-almond-scones/',
    category: 'dessert',
    source: 'From My Bowl',
    prepTime: '30 mins',
    difficulty: 'medium',
  },
  {
    title: 'Lactation Granola',
    description: 'Easy lactation granola - healthy recipe for breastfeeding moms.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/02/Lactation_Granola_FromMyBowl-15-168x168.jpg',
    link: 'https://frommybowl.com/lactation-granola/',
    category: 'breakfast',
    source: 'From My Bowl',
    prepTime: '35 mins',
    difficulty: 'easy',
  },

  // ===== FORKS OVER KNIVES (10 recipes) =====
  {
    title: 'Winter Vegetable Risotto',
    description: 'Creamy winter vegetable risotto with herbs.',
    image: 'https://www.forksoverknives.com/wp-content/uploads/featured-winter-vegetable-risotto.jpg',
    link: 'https://www.forksoverknives.com/recipes/amazing-grains/winter-vegetable-risotto/',
    category: 'dinner',
    source: 'Forks Over Knives',
    prepTime: '40 mins',
    difficulty: 'medium',
  },
  {
    title: 'Crispy Buffalo Cauliflower Bites',
    description: 'Crispy buffalo cauliflower bites - perfect appetizer.',
    image: 'https://www.forksoverknives.com/wp-content/uploads/featured-crispy-buffalo-cauliflower-bites.jpg',
    link: 'https://www.forksoverknives.com/recipes/vegan-snacks-appetizers/crispy-buffalo-cauliflower-bites/',
    category: 'appetizer',
    source: 'Forks Over Knives',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Chickpea Omelet',
    description: 'Fluffy chickpea omelet - high protein breakfast.',
    image: 'https://www.forksoverknives.com/wp-content/uploads/featured-chickpea-omelet.jpg',
    link: 'https://www.forksoverknives.com/recipes/vegan-breakfast/chickpea-omelet/',
    category: 'breakfast',
    source: 'Forks Over Knives',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Indian-Spiced Cauliflower Potato Casserole',
    description: 'Indian-spiced cauliflower and potato casserole.',
    image: 'https://www.forksoverknives.com/wp-content/uploads/featured-indian-spiced-cauliflower-potato-casserole.jpg',
    link: 'https://www.forksoverknives.com/recipes/vegan-baked-stuffed/indian-spiced-cauliflower-potato-easy-vegan-casserole/',
    category: 'dinner',
    source: 'Forks Over Knives',
    prepTime: '45 mins',
    difficulty: 'medium',
  },
  {
    title: 'Creamy Potato Soup',
    description: 'Hearty creamy potato soup with vegetables.',
    image: 'https://www.forksoverknives.com/wp-content/uploads/featured-creamy-potato-soup.jpg',
    link: 'https://www.forksoverknives.com/recipes/vegan-soups-stew/creamy-potato-soup/',
    category: 'soup',
    source: 'Forks Over Knives',
    prepTime: '35 mins',
    difficulty: 'easy',
  },
  {
    title: 'Tuscan White Bean Soup',
    description: 'Tuscan white bean soup with kale.',
    image: 'https://www.forksoverknives.com/wp-content/uploads/featured-tuscan-white-bean-soup.jpg',
    link: 'https://www.forksoverknives.com/recipes/vegan-soups-stew/tuscan-white-bean-soup-kale/',
    category: 'soup',
    source: 'Forks Over Knives',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Thai Green Curry',
    description: 'Flavorful Thai green curry with vegetables.',
    image: 'https://www.forksoverknives.com/wp-content/uploads/featured-thai-green-curry.jpg',
    link: 'https://www.forksoverknives.com/recipes/vegan-curries-stir-fries/thai-green-curry/',
    category: 'dinner',
    source: 'Forks Over Knives',
    prepTime: '35 mins',
    difficulty: 'medium',
  },
  {
    title: 'Chickpea Curry',
    description: 'Easy chickpea curry with spinach.',
    image: 'https://www.forksoverknives.com/wp-content/uploads/featured-chickpea-curry.jpg',
    link: 'https://www.forksoverknives.com/recipes/vegan-curries-stir-fries/chickpea-curry/',
    category: 'dinner',
    source: 'Forks Over Knives',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Lentil Soup',
    description: 'Hearty lentil soup with vegetables.',
    image: 'https://www.forksoverknives.com/wp-content/uploads/featured-lentil-soup.jpg',
    link: 'https://www.forksoverknives.com/recipes/vegan-soups-stew/lentil-soup/',
    category: 'soup',
    source: 'Forks Over Knives',
    prepTime: '40 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Mac and Cheese',
    description: 'Creamy vegan mac and cheese with queso.',
    image: 'https://www.forksoverknives.com/wp-content/uploads/featured-vegan-mac-and-cheese.jpg',
    link: 'https://www.forksoverknives.com/recipes/vegan-pasta/vegan-mac-and-cheese/',
    category: 'pasta',
    source: 'Forks Over Knives',
    prepTime: '30 mins',
    difficulty: 'easy',
  },

  // ===== RAINBOW PLANT LIFE (10 recipes) =====
  {
    title: 'Chili Oil Peanut Noodles',
    description: 'Spicy chili oil peanut noodles in 20 minutes.',
    image: 'https://plantyou.com/wp-content/uploads/2026/03/DSC06924-258x344.jpg',
    link: 'https://plantyou.com/chili-oil-peanut-noodles/',
    category: 'pasta',
    source: 'Rainbow Plant Life',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Easy Vegan Alfredo Pasta',
    description: 'One pot creamy vegan pasta with herbs.',
    image: 'https://plantyou.com/wp-content/uploads/2026/03/DSC06511-258x344.jpg',
    link: 'https://plantyou.com/easy-vegan-alfredo-pasta/',
    category: 'pasta',
    source: 'Rainbow Plant Life',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'One Pot Creamy Pasta',
    description: 'One pot creamy vegan pasta with vegan parmesan.',
    image: 'https://plantyou.com/wp-content/uploads/2026/01/DSC03633-258x344.jpg',
    link: 'https://plantyou.com/one-pot-creamy-pasta/',
    category: 'pasta',
    source: 'Rainbow Plant Life',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Thai Noodle Salad',
    description: 'Meal prep Thai noodle salad in a jar.',
    image: 'https://plantyou.com/wp-content/uploads/2025/06/DSC03594-258x344.jpg',
    link: 'https://plantyou.com/thai-noodle-salad/',
    category: 'salad',
    source: 'Rainbow Plant Life',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Marry Me Chickpeas',
    description: 'Creamy marry me chickpeas - one pan wonder.',
    image: 'https://plantyou.com/wp-content/uploads/2025/04/DSC01281-258x344.png',
    link: 'https://plantyou.com/marry-me-chickpeas/',
    category: 'dinner',
    source: 'Rainbow Plant Life',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Creamy Cucumber Salad',
    description: 'Creamy cucumber salad with dill and lemon.',
    image: 'https://plantyou.com/wp-content/uploads/2025/02/DSC08582-258x344.png',
    link: 'https://plantyou.com/vegan-creamy-cucumber-salad/',
    category: 'salad',
    source: 'Rainbow Plant Life',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Deviled Strawberries',
    description: 'Deviled strawberries with graham cracker crumbs.',
    image: 'https://plantyou.com/wp-content/uploads/2025/04/DSC00954-258x344.png',
    link: 'https://plantyou.com/deviled-strawberries/',
    category: 'dessert',
    source: 'Rainbow Plant Life',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Carrot and Cucumber Salad',
    description: 'Carrot and cucumber salad with lemon dressing.',
    image: 'https://plantyou.com/wp-content/uploads/2026/02/DSC04584-258x344.jpg',
    link: 'https://plantyou.com/carrot-and-cucumber-salad/',
    category: 'salad',
    source: 'Rainbow Plant Life',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Lentil Patties',
    description: 'Lentil patties with creamy vegan dip.',
    image: 'https://plantyou.com/wp-content/uploads/2026/01/DSC04272-258x344.jpg',
    link: 'https://plantyou.com/lentil-patties/',
    category: 'dinner',
    source: 'Rainbow Plant Life',
    prepTime: '35 mins',
    difficulty: 'medium',
  },
  {
    title: 'Vegan Pistachio Ice Cream',
    description: 'Vegan pistachio ice cream in white ramekin.',
    image: 'https://plantyou.com/wp-content/uploads/2025/07/DSC05998-258x344.jpg',
    link: 'https://plantyou.com/vegan-pistachio-ice-cream/',
    category: 'dessert',
    source: 'Rainbow Plant Life',
    prepTime: '20 mins + freeze',
    difficulty: 'medium',
  },

  // ===== PLANT-BASED ON A BUDGET (10 recipes) =====
  {
    title: 'Sticky Lemon Tofu',
    description: 'Sticky lemon tofu - easy vegan dinner.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/06/Lemon-Tofu-8-e1753075891481-378x378.jpg',
    link: 'https://plantbasedonabudget.com/sticky-lemon-tofu/',
    category: 'dinner',
    source: 'Plant-Based on a Budget',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Chipotle Chili Recipe',
    description: 'Spicy chipotle bean chili in a bowl.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/08/Chipotle-Bean-Chili-PBOAB-10-e1755923168334-378x378.jpg',
    link: 'https://plantbasedonabudget.com/chipotle-chili-recipe/',
    category: 'soup',
    source: 'Plant-Based on a Budget',
    prepTime: '35 mins',
    difficulty: 'easy',
  },
  {
    title: 'Cream of Celery Soup',
    description: 'Creamy celery soup in a bowl.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/09/Celery-Soup-9-e1757134677362-378x378.jpg',
    link: 'https://plantbasedonabudget.com/cream-of-celery-soup/',
    category: 'soup',
    source: 'Plant-Based on a Budget',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Easy Lentil Salad',
    description: 'Easy lentil salad on a plate.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/02/Lentil-Salad-PBOAB-13-378x378.jpg',
    link: 'https://plantbasedonabudget.com/easy-lentil-salad/',
    category: 'salad',
    source: 'Plant-Based on a Budget',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Lemongrass Tofu',
    description: 'Lemongrass tofu on a plate.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/05/Lemongrass-Tofu-10-e1752956757500-378x378.jpg',
    link: 'https://plantbasedonabudget.com/lemongrass-tofu/',
    category: 'dinner',
    source: 'Plant-Based on a Budget',
    prepTime: '30 mins',
    difficulty: 'medium',
  },
  {
    title: 'Easy Curried Chickpea Salad',
    description: 'Easy curried chickpea salad on a plate.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/02/Curried-Chickpea-Salad-Plant-Based-on-a-Budget-12-378x378.jpg',
    link: 'https://plantbasedonabudget.com/easy-curried-chickpea-salad/',
    category: 'salad',
    source: 'Plant-Based on a Budget',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Alphabet Soup Recipe',
    description: 'Fun alphabet soup in a bowl.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/02/Alphabet-Soup-PBOAB-14-378x378.jpg',
    link: 'https://plantbasedonabudget.com/alphabet-soup-recipe/',
    category: 'soup',
    source: 'Plant-Based on a Budget',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Easy Tempeh Tacos',
    description: 'Easy tempeh tacos on a white surface.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2024/06/Tempeh-Tacos-PBOAB-Plant-Based-on-a-Budget-41-378x378.jpg',
    link: 'https://plantbasedonabudget.com/easy-tempeh-tacos/',
    category: 'dinner',
    source: 'Plant-Based on a Budget',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Peanut Butter Cake',
    description: 'Vegan peanut butter cake on a plate.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/08/Peanut-Butter-Cake-13-e1755237355177-378x378.jpg',
    link: 'https://plantbasedonabudget.com/vegan-peanut-butter-cake/',
    category: 'dessert',
    source: 'Plant-Based on a Budget',
    prepTime: '40 mins',
    difficulty: 'medium',
  },
  {
    title: 'Gingerbread Crinkle Cookies',
    description: 'Gingerbread crinkle cookies on a baking dish.',
    image: 'https://plantbasedonabudget.com/wp-content/uploads/2025/10/Ginger-Crinkle-Cookies-PBOAB-14-e1759520798323-378x378.jpg',
    link: 'https://plantbasedonabudget.com/gingerbread-crinkle-cookies-eggless/',
    category: 'dessert',
    source: 'Plant-Based on a Budget',
    prepTime: '25 mins',
    difficulty: 'easy',
  },

  // ===== SWEET POTATO SOUL (10 recipes) =====
  {
    title: 'Sweet Potato Chickpea Curry',
    description: 'Hearty chickpea curry with sweet potatoes and coconut milk.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2025/03/delicious-vegan-chickpea-curry-768x960.jpg',
    link: 'https://sweetpotatosoul.com/sweet-potato-chickpea-curry/',
    category: 'dinner',
    source: 'Sweet Potato Soul',
    prepTime: '35 mins',
    difficulty: 'easy',
  },
  {
    title: 'Easy Vegan Lentil Tacos',
    description: 'Easy lentil tacos ready in 10 minutes.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2024/01/Easy-Vegan-Lentil-Tacos-768x960.jpg',
    link: 'https://sweetpotatosoul.com/sculpting-kitchen-workout-lentil-tacos-with-mango-guacamole-video/',
    category: 'dinner',
    source: 'Sweet Potato Soul',
    prepTime: '10 mins',
    difficulty: 'easy',
  },
  {
    title: 'Chickpea Tuna Salad',
    description: 'Vegan chickpea tuna salad - creamy and zesty.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2024/04/Vegan-chickpea-tuna-salad-768x960.jpg',
    link: 'https://sweetpotatosoul.com/vegan-chickpea-tuna-salad-video/',
    category: 'lunch',
    source: 'Sweet Potato Soul',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Jamaican Chickpea Curry',
    description: 'Spicy Jamaican curry with chickpeas.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2025/09/jamaican-chickpea-curry-768x960.jpg',
    link: 'https://sweetpotatosoul.com/jamaican-chickpea-curry/',
    category: 'dinner',
    source: 'Sweet Potato Soul',
    prepTime: '30 mins',
    difficulty: 'medium',
  },
  {
    title: 'Vegan Lentil Meatloaf',
    description: 'Hearty vegan lentil meatloaf with mushroom gravy.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2024/05/vegan-lentil-meatloaf-768x960.jpeg',
    link: 'https://sweetpotatosoul.com/vegan-lentil-meatloaf/',
    category: 'dinner',
    source: 'Sweet Potato Soul',
    prepTime: '50 mins',
    difficulty: 'medium',
  },
  {
    title: 'Vegan Burrito Bowl',
    description: 'Better-than-Chipotle vegan burrito bowl.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2020/02/Vegan-Taco-Bowl.jpeg',
    link: 'https://sweetpotatosoul.com/ultimate-vegan-burrito-bowl/',
    category: 'dinner',
    source: 'Sweet Potato Soul',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Caesar Salad',
    description: 'Best vegan Caesar salad with crispy chickpeas.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2024/05/vegan-caesar-salad-768x960.jpeg',
    link: 'https://sweetpotatosoul.com/best-vegan-caesar-salad/',
    category: 'salad',
    source: 'Sweet Potato Soul',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Fried Chicken',
    description: 'Vegan fried cauliflower "chicken" with double batter.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2017/04/Cauliflower-Vegan-Fried-Chicken-768x960.jpeg',
    link: 'https://sweetpotatosoul.com/vegan-fried-cauliflower-chicken-soul-food-sunday-video/',
    category: 'dinner',
    source: 'Sweet Potato Soul',
    prepTime: '40 mins',
    difficulty: 'hard',
  },
  {
    title: 'Sweet Potato Soup',
    description: 'Creamy sweet potato soup with crispy white beans.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2024/11/sweet-potato-soup-in-bowl-768x960.jpg',
    link: 'https://sweetpotatosoul.com/sweet-potato-bisque-with-crispy-white-beans/',
    category: 'soup',
    source: 'Sweet Potato Soul',
    prepTime: '35 mins',
    difficulty: 'easy',
  },
  {
    title: 'Mango Sorbet',
    description: 'Easy 3-ingredient mango sorbet - no ice cream maker.',
    image: 'https://sweetpotatosoul.com/wp-content/uploads/2025/05/no-churn-mango-sorbet-768x960.jpg',
    link: 'https://sweetpotatosoul.com/mango-sorbet/',
    category: 'dessert',
    source: 'Sweet Potato Soul',
    prepTime: '10 mins + freeze',
    difficulty: 'easy',
  },

  // ===== PLANT BASED RD (10 recipes) =====
  {
    title: 'Dan Dan Charred Cabbage',
    description: 'Charred cabbage with Dan Dan sauce, tofu, and peanuts.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2025/05/Dan-Dan-Charred-Cabbage-819x1024.jpg',
    link: 'https://plantbasedrdblog.com/2025/05/dan-dan-charred-cabbage/',
    category: 'dinner',
    source: 'Plant Based RD',
    prepTime: '30 mins',
    difficulty: 'medium',
  },
  {
    title: 'Charred Lemon Brothy Beans',
    description: 'White beans with charred lemon and avocado salsa.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2025/01/Charred-Lemon-Brothy-Beans-819x1024.jpg',
    link: 'https://plantbasedrdblog.com/2025/01/charred-lemon-brothy-beans/',
    category: 'dinner',
    source: 'Plant Based RD',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Pumpkin Coffee Cake Chia Pudding',
    description: 'Pumpkin chia pudding with streusel topping.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2025/09/Pumpkin-Coffee-Cake-Chia-Pudding-819x1024.jpg',
    link: 'https://plantbasedrdblog.com/2025/09/pumpkin-coffee-cake-chia-pudding/',
    category: 'breakfast',
    source: 'Plant Based RD',
    prepTime: '15 mins + chill',
    difficulty: 'easy',
  },
  {
    title: 'Whole Roasted Cauliflower',
    description: 'Whole roasted cauliflower with scallion date dressing.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2025/02/Whole-Roasted-Cauliflower-819x1024.jpg',
    link: 'https://plantbasedrdblog.com/2025/02/whole-roasted-cauliflower-with-creamy-scallion-date-dressing/',
    category: 'dinner',
    source: 'Plant Based RD',
    prepTime: '45 mins',
    difficulty: 'medium',
  },
  {
    title: 'Chipotle Lime Black Bean Bowls',
    description: 'Black bean bowls with chipotle lime sauce.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2023/12/chipotle-lime-black-bean-bowls_feat.jpg',
    link: 'https://plantbasedrdblog.com/2023/12/chipotle-lime-black-bean-bowls/',
    category: 'lunch',
    source: 'Plant Based RD',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Chili Lime Chickpea Cauliflower Wrap',
    description: 'Pita wrap with chickpeas, cauliflower, and chipotle.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2024/01/chili-lime-roasted-cauliflower-chickpeas_feat.jpg',
    link: 'https://plantbasedrdblog.com/2024/01/chili-lime-chickpea-cauliflower-wrap/',
    category: 'lunch',
    source: 'Plant Based RD',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Marinated Cilantro Lime Bean Salad',
    description: 'Marinated bean salad with cilantro and lime.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2025/05/Marinated-Cilantro-Lime-Bean-Salad-819x1024.jpg',
    link: 'https://plantbasedrdblog.com/2025/05/marinated-cilantro-lime-bean-salad/',
    category: 'salad',
    source: 'Plant Based RD',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Black Bean Taquitos',
    description: 'Black bean taquitos with salsa roja.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2025/05/black-bean-taquitos-819x1024.jpg',
    link: 'https://plantbasedrdblog.com/2025/05/black-bean-taquitos-with-salsa-roja/',
    category: 'appetizer',
    source: 'Plant Based RD',
    prepTime: '30 mins',
    difficulty: 'medium',
  },
  {
    title: 'Caramelized Onion Chickpea Salad Sandwich',
    description: 'Sandwich with caramelized onions and chickpea salad.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2024/03/caramelized-onion-chickpea-salad-sandwich_feat.jpg',
    link: 'https://plantbasedrdblog.com/2024/03/caramelized-onion-chickpea-salad-sandwich/',
    category: 'lunch',
    source: 'Plant Based RD',
    prepTime: '20 mins',
    difficulty: 'easy',
  },
  {
    title: 'Buffalo Tofu Cutlets',
    description: 'Buffalo tofu cutlets with celery ranch slaw.',
    image: 'https://plantbasedrdblog.com/wp-content/uploads/2024/07/buffalo-tofu-cutlets_feat.jpg',
    link: 'https://plantbasedrdblog.com/2024/07/buffalo-tofu-cutlets-with-celery-ranch-slaw/',
    category: 'dinner',
    source: 'Plant Based RD',
    prepTime: '30 mins',
    difficulty: 'medium',
  },

  // ===== IT DOESN'T TASTE LIKE CHICKEN (10 recipes) =====
  {
    title: 'Loaded Vegan Nachos',
    description: 'Sheet pan of loaded vegan nachos.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2015/08/Vegan-Nachos-hero-720x1062.jpg',
    link: 'https://itdoesnttastelikechicken.com/loaded-vegan-nachos/',
    category: 'appetizer',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Dense Bean Salad',
    description: 'Bowl of dense bean salad.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2026/03/Dense-Bean-Salad-hero-720x1062.jpg',
    link: 'https://itdoesnttastelikechicken.com/dense-bean-salad/',
    category: 'salad',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Cheesy Vegan Garlic Bread',
    description: 'Two loaves of vegan garlic bread.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2019/02/Vegan-Garlic-Bread-hero-720x1062.jpg',
    link: 'https://itdoesnttastelikechicken.com/cheesy-vegan-garlic-bread/',
    category: 'side',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Air Fryer Sweet Potatoes',
    description: 'Platter of air fryer sweet potatoes.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2026/03/Air-Fryer-Sweet-Potatoes-hero-720x1062.jpg',
    link: 'https://itdoesnttastelikechicken.com/air-fryer-sweet-potatoes/',
    category: 'side',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Pistachio Butter',
    description: 'Jar of homemade pistachio butter.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2026/03/Pistachio-Butter-hero-720x1062.jpg',
    link: 'https://itdoesnttastelikechicken.com/pistachio-butter/',
    category: 'sauce',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '10 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vanilla Mug Cake',
    description: 'Mug cake with sprinkles and whipped cream.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2026/03/Vanilla-Mug-Cake-hero-720x1062.jpg',
    link: 'https://itdoesnttastelikechicken.com/vanilla-mug-cake/',
    category: 'dessert',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '5 mins',
    difficulty: 'easy',
  },
  {
    title: 'Fudgy Vegan Brownies',
    description: 'Ultra-chocolatey, decadent one-bowl brownies.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2026/02/Fudgy-Vegan-Brownies-hero-720x1062.jpg',
    link: 'https://itdoesnttastelikechicken.com/easy-fudgy-vegan-brownies/',
    category: 'dessert',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '35 mins',
    difficulty: 'easy',
  },
  {
    title: 'Easy Red Lentil Curry',
    description: 'Quick, creamy, flavorful curry ready in 40 minutes.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2025/01/Easy-Red-Lentil-Curry-hero-720x1062.jpg',
    link: 'https://itdoesnttastelikechicken.com/easy-red-lentil-curry/',
    category: 'dinner',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '40 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Egg Roll in a Bowl',
    description: 'Tastes like egg rolls but without the wrapper.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2020/08/Vegan-Egg-Roll-in-a-Bowl-hero-720x1062.jpg',
    link: 'https://itdoesnttastelikechicken.com/vegan-egg-roll-in-a-bowl/',
    category: 'dinner',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Easy Vegan Zucchini Bread',
    description: 'Moist, tender, fluffy zucchini bread with cinnamon.',
    image: 'https://itdoesnttastelikechicken.com/wp-content/uploads/2018/07/Easy-Vegan-Zucchini-Bread-hero-720x1062.jpg',
    link: 'https://itdoesnttastelikechicken.com/easy-vegan-zucchini-bread/',
    category: 'breakfast',
    source: 'It Doesn\'t Taste Like Chicken',
    prepTime: '70 mins',
    difficulty: 'easy',
  },

  // ===== THAT VEGAN BABE (10 recipes) =====
  {
    title: 'Sheet Pan Gnocchi',
    description: 'Sheet pan gnocchi with tahini herb sauce.',
    image: 'https://i0.wp.com/thatveganbabe.com/wp-content/uploads/easyindex/280x280/thumb-13909.jpg?w=1200',
    link: 'https://thatveganbabe.com/sheet-pan-gnocchi/',
    category: 'pasta',
    source: 'That Vegan Babe',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Caprese Toast',
    description: 'Caprese toast with tomatoes and basil.',
    image: 'https://i0.wp.com/thatveganbabe.com/wp-content/uploads/easyindex/280x280/thumb-13496.jpg?w=1200',
    link: 'https://thatveganbabe.com/caprese-toast/',
    category: 'breakfast',
    source: 'That Vegan Babe',
    prepTime: '10 mins',
    difficulty: 'easy',
  },
  {
    title: 'Kale Pesto Pasta',
    description: 'Kale pesto pasta - 15 minute meal.',
    image: 'https://i0.wp.com/thatveganbabe.com/wp-content/uploads/easyindex/280x280/thumb-13332.jpg?w=1200',
    link: 'https://thatveganbabe.com/kale-pesto-pasta/',
    category: 'pasta',
    source: 'That Vegan Babe',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Lemon Blueberry Breakfast Cake',
    description: 'Lemon blueberry breakfast cake.',
    image: 'https://i0.wp.com/thatveganbabe.com/wp-content/uploads/easyindex/280x280/thumb-14782.jpg?w=1200',
    link: 'https://thatveganbabe.com/lemon-blueberry-breakfast-cake/',
    category: 'breakfast',
    source: 'That Vegan Babe',
    prepTime: '35 mins',
    difficulty: 'medium',
  },
  {
    title: 'Chocolate Breakfast Quinoa Bake',
    description: 'Chocolate breakfast quinoa bake.',
    image: 'https://i0.wp.com/thatveganbabe.com/wp-content/uploads/easyindex/280x280/thumb-14481.jpg?w=1200',
    link: 'https://thatveganbabe.com/chocolate-breakfast-quinoa-bake/',
    category: 'breakfast',
    source: 'That Vegan Babe',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Tiramisu Baked Oats',
    description: 'Tiramisu flavored baked oats.',
    image: 'https://i0.wp.com/thatveganbabe.com/wp-content/uploads/easyindex/280x280/thumb-14456.jpg?w=1200',
    link: 'https://thatveganbabe.com/tiramisu-baked-oats/',
    category: 'breakfast',
    source: 'That Vegan Babe',
    prepTime: '35 mins',
    difficulty: 'easy',
  },
  {
    title: 'Homemade Collagen Gummies',
    description: 'Healthy homemade collagen gummies.',
    image: 'https://i0.wp.com/thatveganbabe.com/wp-content/uploads/easyindex/280x280/thumb-14579.jpg?w=1200',
    link: 'https://thatveganbabe.com/homemade-collagen-gummies/',
    category: 'snack',
    source: 'That Vegan Babe',
    prepTime: '20 mins + set',
    difficulty: 'medium',
  },
  {
    title: 'Easy Protein Cinnamon Rolls',
    description: 'High protein cinnamon rolls.',
    image: 'https://i0.wp.com/thatveganbabe.com/wp-content/uploads/easyindex/280x280/thumb-14018.jpg?w=1200',
    link: 'https://thatveganbabe.com/protein-cinnamon-rolls/',
    category: 'dessert',
    source: 'That Vegan Babe',
    prepTime: '45 mins',
    difficulty: 'medium',
  },
  {
    title: 'Viral Chocolate Rice Pudding',
    description: 'Viral chocolate rice pudding.',
    image: 'https://i0.wp.com/thatveganbabe.com/wp-content/uploads/easyindex/280x280/thumb-13288.jpg?w=1200',
    link: 'https://thatveganbabe.com/chocolate-rice-pudding/',
    category: 'dessert',
    source: 'That Vegan Babe',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Tiramisu Protein Balls',
    description: 'Tiramisu flavored protein balls.',
    image: 'https://i0.wp.com/thatveganbabe.com/wp-content/uploads/easyindex/280x280/thumb-13417.jpg?w=1200',
    link: 'https://thatveganbabe.com/tiramisu-protein-balls/',
    category: 'snack',
    source: 'That Vegan Babe',
    prepTime: '15 mins',
    difficulty: 'easy',
  },

  // ===== VEGANUARY (10 recipes) =====
  {
    title: 'Noodles with Miso-Tahini Sauce',
    description: 'Udon or lo mein with miso-tahini sauce.',
    image: 'https://veganuary.com/wp-content/uploads/2016/07/Noodles-with-Miso-Tahini-Sauce-400x290.jpg',
    link: 'https://veganuary.com/en-us/recipes/noodles-with-miso-tahini-sauce',
    category: 'pasta',
    source: 'Veganuary',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Sesame Sushi with Ginger-Tamari Sauce',
    description: 'Perfect vegan sushi with ginger-tamari dipping sauce.',
    image: 'https://veganuary.com/wp-content/uploads/2016/07/Brown-Rice-Sesame-Sushi-400x290.jpg',
    link: 'https://veganuary.com/en-us/recipes/brown-rice-sesame-sushi-with-ginger-tamari-dipping-sauce/',
    category: 'dinner',
    source: 'Veganuary',
    prepTime: '45 mins',
    difficulty: 'medium',
  },
  {
    title: 'Gazpacho',
    description: 'Sweet and slightly sour chilled tomato soup.',
    image: 'https://veganuary.com/wp-content/uploads/2016/07/Gazpacho-400x290.jpg',
    link: 'https://veganuary.com/en-us/recipes/gazpacho/',
    category: 'soup',
    source: 'Veganuary',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Mushroom Stroganoff',
    description: 'Creamy wild mushroom stroganoff with macadamia milk.',
    image: 'https://veganuary.com/wp-content/uploads/2023/08/Vegan-Mushroom-Stroganoff-400x400.jpg',
    link: 'https://veganuary.com/en-us/recipes/vegan-mushroom-stroganoff/',
    category: 'pasta',
    source: 'Veganuary',
    prepTime: '30 mins',
    difficulty: 'medium',
  },
  {
    title: 'Choc & Peanut Butter Oatmeal',
    description: 'Chocolate and peanut butter oatmeal - sweet breakfast.',
    image: 'https://veganuary.com/wp-content/uploads/2021/01/Choc-Peanut-Butter-Oatmeal-400x400.jpg',
    link: 'https://veganuary.com/en-us/recipes/choc-peanut-butter-oatmeal/',
    category: 'breakfast',
    source: 'Veganuary',
    prepTime: '10 mins',
    difficulty: 'easy',
  },
  {
    title: 'Vegan Butter Chicken',
    description: 'Mushroom-based butter chicken with creamy sauce.',
    image: 'https://veganuary.com/wp-content/uploads/2021/01/Vegan-Butter-Chicken-400x400.jpg',
    link: 'https://veganuary.com/en-us/recipes/vegan-butter-chicken',
    category: 'dinner',
    source: 'Veganuary',
    prepTime: '35 mins',
    difficulty: 'medium',
  },
  {
    title: 'Chickpea and Sweet Potato Curry with Cauliflower Rice',
    description: 'Spiced curry with cauliflower rice.',
    image: 'https://veganuary.com/wp-content/uploads/2016/02/Chickpea-and-Sweet-Potato-Curry-400x290.jpg',
    link: 'https://veganuary.com/en-us/recipes/chickpea-and-sweet-potato-curry-with-cauliflower-rice',
    category: 'dinner',
    source: 'Veganuary',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Big Puff Pie',
    description: 'Hearty stew with puff pastry lid.',
    image: 'https://veganuary.com/wp-content/uploads/2015/02/Big-Puff-Pie-400x290.jpg',
    link: 'https://veganuary.com/en-us/recipes/big-puff-pie',
    category: 'dinner',
    source: 'Veganuary',
    prepTime: '35 mins',
    difficulty: 'medium',
  },
  {
    title: 'Lentil Lasagna',
    description: 'Gluten-free vegan lasagna with cashew sauce.',
    image: 'https://veganuary.com/wp-content/uploads/2014/09/Lentil-Lasagna-400x290.jpg',
    link: 'https://veganuary.com/en-us/recipes/lentil-lasagna',
    category: 'dinner',
    source: 'Veganuary',
    prepTime: '60 mins',
    difficulty: 'hard',
  },
  {
    title: 'Cheesy Vegan Potato Bake',
    description: 'Comforting potato bake with vegan cheese sauce.',
    image: 'https://veganuary.com/wp-content/uploads/2021/01/Cheesy-Vegan-Potato-Bake-400x400.jpg',
    link: 'https://veganuary.com/en-us/recipes/cheesy-vegan-potato-bake',
    category: 'side',
    source: 'Veganuary',
    prepTime: '80 mins',
    difficulty: 'easy',
  },
];
