import { Recipe, RecipeCategory } from './types';

export const recipes: Recipe[] = [
  // ===== THE PLANT BASED SCHOOL (10 recipes) =====
  {
    title: 'No Bake Oat Bars',
    description: 'Soft and chewy no bake oat bars with nuts, seeds, and cranberries.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Soft-and-chewy-no-bake-oat-bars-with-nuts-seeds-and-cranberries-on-a-marble-countertop-600x600.jpg',
    link: 'https://theplantbasedschool.com/no-bake-oat-bars/',
    category: 'breakfast',
    source: 'The Plant Based School',
    prepTime: '15 mins',
    difficulty: 'easy',
  },
  {
    title: 'Peanut Butter Energy Balls',
    description: 'No-bake peanut butter energy balls served chilled on a marble table.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/No-bake-peanut-butter-energy-balls-served-chilled-on-a-marble-table-600x600.jpg',
    link: 'https://theplantbasedschool.com/peanut-butter-energy-balls/',
    category: 'snack',
    source: 'The Plant Based School',
    prepTime: '10 mins',
    difficulty: 'easy',
  },
  {
    title: 'Peanut Butter Banana Muffins',
    description: 'Peanut butter banana muffins stacked on marble table with creamy drizzle.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Peanut-butter-banana-muffins-stacked-on-marble-table-with-creamy-drizzle-and-oats-in-soft-natural-light-600x600.jpg',
    link: 'https://theplantbasedschool.com/peanut-butter-banana-muffins/',
    category: 'breakfast',
    source: 'The Plant Based School',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Chia Pudding Recipes',
    description: 'Three versions of healthy chia pudding recipes.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Three-versions-of-healthy-chia-pudding-recipes-600x600.jpg',
    link: 'https://theplantbasedschool.com/chia-pudding-recipes/',
    category: 'breakfast',
    source: 'The Plant Based School',
    prepTime: '10 mins',
    difficulty: 'easy',
  },
  {
    title: 'Lentil Noodle Soup',
    description: 'Rustic bowl filled with lentil noodle soup and fresh parsley.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/02/Rustic-bowl-filled-with-lentil-noodle-soup-and-fresh-parsley-on-top-600x600.jpg',
    link: 'https://theplantbasedschool.com/lentil-noodle-soup/',
    category: 'soup',
    source: 'The Plant Based School',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Chickpea Noodle Soup',
    description: 'Cozy bowl of chickpea noodle soup served hot with olive oil.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/02/Cozy-bowl-of-chickpea-noodle-soup-served-hot-with-olive-oil-and-grated-Parmesan-600x600.jpg',
    link: 'https://theplantbasedschool.com/chickpea-noodle-soup/',
    category: 'soup',
    source: 'The Plant Based School',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Marry Me Gnocchi',
    description: 'Spoon lifting creamy marry me gnocchi with spinach.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Spoon-lifting-creamy-marry-me-gnocchi-showing-soft-texture-and-rich-sauce-with-spinach-600x600.jpg',
    link: 'https://theplantbasedschool.com/marry-me-gnocchi/',
    category: 'pasta',
    source: 'The Plant Based School',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Orzo Primavera',
    description: 'Bowl of orzo primavera with basil and black pepper.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/03/Bowl-of-orzo-primavera-with-basil-and-black-pepper-600x600.jpg',
    link: 'https://theplantbasedschool.com/orzo-primavera/',
    category: 'pasta',
    source: 'The Plant Based School',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'Falafel Burger',
    description: 'Falafel burger stacked with lettuce, tomato, and sauce.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Falafel-burger-stacked-with-lettuce-tomato-and-sauce-styled-on-marble-in-bright-light-600x600.jpg',
    link: 'https://theplantbasedschool.com/falafel-burger/',
    category: 'dinner',
    source: 'The Plant Based School',
    prepTime: '30 mins',
    difficulty: 'medium',
  },
  {
    title: 'Pinto Bean Salad',
    description: 'Pinto bean salad in simple bowl near window with bright light.',
    image: 'https://theplantbasedschool.com/wp-content/uploads/2026/04/Pinto-bean-salad-served-in-simple-bowl-near-window-with-bright-natural-light-and-fresh-colors-600x600.jpg',
    link: 'https://theplantbasedschool.com/pinto-bean-salad/',
    category: 'salad',
    source: 'The Plant Based School',
    prepTime: '20 mins',
    difficulty: 'easy',
  },

  // ===== FROM MY BOWL (10 recipes) =====
  {
    title: 'Easy Roasted Veggie Pasta',
    description: 'Easy roasted veggie pasta with mushrooms.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/04/Roasted_Veggie_Pasta_FromMyBowl-12-168x168.jpg',
    link: 'https://frommybowl.com/easy-roasted-veggie-pasta-with-mushrooms/',
    category: 'pasta',
    source: 'From My Bowl',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Sheet Pan Black Bean Quesadillas',
    description: 'Sheet pan black bean corn quesadillas - easy no-chop recipe.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/04/Sheet_Pan_Black_Bean_Corn_Quesadillas_Vegan_FromMyBowl-13-168x168.jpg',
    link: 'https://frommybowl.com/sheet-pan-black-bean-corn-quesadillas/',
    category: 'dinner',
    source: 'From My Bowl',
    prepTime: '25 mins',
    difficulty: 'easy',
  },
  {
    title: 'High Fiber Chia Pudding',
    description: 'Easy high protein chia pudding with no protein powder.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/03/High_Protein_Chia_Pudding_Vegan_FromMyBowl-11-168x168.jpg',
    link: 'https://frommybowl.com/high-protein-chia-pudding/',
    category: 'breakfast',
    source: 'From My Bowl',
    prepTime: '10 mins',
    difficulty: 'easy',
  },
  {
    title: 'Baked Raspberry Oatmeal',
    description: 'Healthy baked raspberry oatmeal - easy one dish recipe.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/03/Baked_Raspberry_Oatmeal_Vegan_FromMyBowl-10-168x168.jpg',
    link: 'https://frommybowl.com/healthy-baked-raspberry-oatmeal/',
    category: 'breakfast',
    source: 'From My Bowl',
    prepTime: '35 mins',
    difficulty: 'easy',
  },
  {
    title: 'Spinach Artichoke Soup',
    description: 'Spinach artichoke soup with white beans - dairy-free.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/03/Spinach_Artichoke_White_Bean_Soup_FromMyBowl_Vegan-13-168x168.jpg',
    link: 'https://frommybowl.com/spinach-artichoke-soup-with-white-beans/',
    category: 'soup',
    source: 'From My Bowl',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Roasted Curry Cauliflower',
    description: 'Roasted curry cauliflower - simple, vibrant, and delicious.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/03/Roasted_Curry_Cauliflower_Vegan_FromMyBowl-14-168x168.jpg',
    link: 'https://frommybowl.com/roasted-curry-cauliflower-recipe/',
    category: 'side',
    source: 'From My Bowl',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'Yellow Cauliflower Chickpea Curry',
    description: 'Easy yellow cauliflower chickpea curry with coconut milk.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/02/Yellow_Cauliflower_Chickpea_Curry_Vegan_FromMyBowl-13-168x168.jpg',
    link: 'https://frommybowl.com/yellow-cauliflower-chickpea-curry/',
    category: 'dinner',
    source: 'From My Bowl',
    prepTime: '30 mins',
    difficulty: 'easy',
  },
  {
    title: 'One Pan Vegan Massaman Curry',
    description: 'One pan vegan massaman curry with potatoes and tofu.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/02/One_Pan_Vegan_Massaman_Curry_FromMyBowl-13-168x168.jpg',
    link: 'https://frommybowl.com/one-pan-vegan-massaman-curry/',
    category: 'dinner',
    source: 'From My Bowl',
    prepTime: '35 mins',
    difficulty: 'medium',
  },
  {
    title: 'Cherry Almond Scones',
    description: 'Easy cherry almond scones with cherry glaze.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/02/Cherry_Almond_Scones_Vegan_FromMyBowl-16-168x168.jpg',
    link: 'https://frommybowl.com/cherry-almond-scones/',
    category: 'dessert',
    source: 'From My Bowl',
    prepTime: '30 mins',
    difficulty: 'medium',
  },
  {
    title: 'Lactation Granola',
    description: 'Easy lactation granola - healthy recipe for breastfeeding moms.',
    image: 'https://frommybowl.com/wp-content/uploads/2026/02/Lactation_Granola_FromMyBowl-15-168x168.jpg',
    link: 'https://frommybowl.com/lactation-granola/',
    category: 'breakfast',
    source: 'From My Bowl',
    prepTime: '35 mins',
    difficulty: 'easy',
  },
];
